# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  log-level:
    default: info
    description: Temporal server logging level.
    type: string
  server-name:
    description: |
        The name with which the Temporal server frontend service is deployed.
    default: "temporal-k8s"
    type: string
