name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      provider: microk8s
      channel: 1.25-strict/stable
      juju-channel: 3.1/stable
