name: Integration tests
on:
  pull_request:
  workflow_call:
jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: |
        --kube-config=~/.kube/config
      use-canonical-k8s: true
      channel: edge
      charmcraft-channel: latest/edge
      modules: '["test_charm.py", "test_refresh.py"]'
      juju-channel: 3.6/stable
